/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Ignore;
import org.junit.Test;
import ru.vershinin.game.AttempResult;
import ru.vershinin.game.Game;
import ru.vershinin.game.WrongLengthExeption;

import static org.junit.Assert.assertEquals;


@Ignore
public class AppTest {

    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(AppTest.class);

    @Test public void test() {

        Game game = Game.getNewGame();

        String word = game.getSecretWord();

        try {
            game.attempt(word + "t");
        } catch (WrongLengthExeption wrongLengthExeption) {
            assertEquals("Wrong word lenght", wrongLengthExeption.getMessage());
        }

        try {
            AttempResult attempResult2 = game.attempt(word);

            assertEquals(true, attempResult2.getResult());
            assertEquals(word.length(), attempResult2.getBulls());
            assertEquals(word.length(), attempResult2.getCows());
            assertEquals(1, attempResult2.getAttemptNumber());
        } catch (WrongLengthExeption wrongLengthExeption) {
            log.error(wrongLengthExeption.getMessage());
        }

    }
}
